Kafka Consumer
mai-806/Delivery.Metrics pull request #14
Opened 2023-07-08 13:55 UTC by SomebodyGit

Написать функцию, которая:
1 - Делает запрос к кафке
2 - Возвращает полученный результат

2023-07-08 13:55 UTC, Kofre-chist approved these changes

2023-07-08 19:01 UTC, Yeloki requested changes

2023-07-08 19:01 UTC, Yeloki commented on Kafka_consumer.py
> +        return message.value.decode('utf-8')
не будет работать, т.к. произойдет return на первой итерации, а остальных сообщений никто не увидит.

2023-07-08 19:01 UTC, Yeloki commented on Kafka_consumer.py
> +        return message.value.decode('utf-8')
data = []
...
data.append(...)
...
return data

2023-07-08 21:08 UTC, Kofre-chist approved these changes
Да, теперь всё работает как надо

2023-07-09 01:16 UTC, Yeloki requested changes

2023-07-09 01:16 UTC, Yeloki commented on Kafka_consumer.py
> +                print(message.value.decode('utf-8'))
Я не вижу, чтобы он возвращал полученный результат. Я вижу вывод в консоль

2023-07-09 11:00 UTC, Kofre-chist approved these changes

2023-07-10 18:19 UTC, merged